server:
  display-name: Borrowers services
  port: 8090

# management endpoints on an other port
management:
  port: 8091
  security:
    enabled: false

logging:
  log: logs/borrowers-services.log

spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/mysql_db_borrowers
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    testOnBorrow: true
    testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      dll-auto: validate

# management database migration
flyway:
  check-location: true
  locations: classpath:/db/migration