server:
  display-name: Borrowers services
  port: 8090

# management endpoints on an other port
management:
  server:
    port: 8091
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file:
    name: logs/borrowers-services.log
  level:
    org.springframework.jdbc.core: DEBUG
    com.zaxxer.hikari: DEBUG
    org.flywaydb: DEBUG
    org.hibernate: DEBUG

spring:
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_db_borrowers
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    testOnBorrow: true
    testWhileIdle: true # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      dll-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        id:
          new_generator_mappings: false
          use-new-id-generator-mappings: false
  # management database migration
  flyway:
    check-location: true
    locations: classpath:/db/migration


# Add SpringDoc configuration here
springdoc:
  package-to-scan: com.mmik.challenge.capita.*
  paths-to-match: /api/borrowers/**
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html